### ISSUE TITLE
Aggiornamento stato valvole ...

### ISSUE THREAD

**Issue by spippolone** [lejubila/piGardenWeb#10]
Con utente non loggato l'aggiornamento dello stato valvole funziona correttamente. Con utente registrato e loggato invece l'aggiornamento non funziona.

Utiliizando firefox nella modalità debug ho notato che quando l'utente non è loggato viene effetuata una richiesta JSON all'indirizzo:
```
http://192.168.x.x/piGardenWeb/public/jsonDashboardStatus
```
E si ottiene risposta:
```
status | {…}
zones | {…}
error | {…}
weather | null
last_rain_sensor | 17/06/2018 17:09
last_rain_online | sconosciuto
cron_open_in | []
messages | []
```
Quando l'utente non è loggato viene invece effetuata una richiesta JSON all'indirizzo:
```
http://192.168.x.x/piGardenWeb/public/admim/jsonDashboardStatus
```
E si ottiene risposta errata:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /jsonDashboardStatus was not found on this server.</p>
<hr>
<address>Apache/2.4.10 (Raspbian) Server at 192.168.x.x Port 80</address>
</body></html>
```
Perchè con utente loggato c'è questo errore ?

**Comment by lejubila** [comment]
piGardenWeb richiede il modulo rewrite di Apache abilitato. Assicurati che lo sia perché sospetto sia questo il problema.

**Comment by spippolone** [comment]
Ciao David,
Il modulo Apache è attivo ...

Ciao Sergio

2018-06-17 17:26 GMT+02:00 David Bigagli <notifications@github.com>:

**Comment by lejubila** [comment]
Potrebbe essere un problema di percorso.
piGardenWeb è stato concepito per funzionare sulla document root del web server.
Prova a prendere spunto dal file di configurazione di apache presente in piGardenWeb/edit/master/virtualhost/apache/piGarden.conf
in modo che la root di piGadernWeb risponda direttamente su http://192.168.x.x/

**Comment by spippolone** [comment]
Ciao scusa del ritardo nella risposta ma ho avuto un perioduccio... non lo
posso mettere nella root, su quell'arduino io ho anche la gestione del
fotovoltaico, dell'allarme di casa, del cancello elettrico..
il problema è che quando sei admin loggato non risponde più
all'interrogazione json che invece fa da utente guest, quindi non è un
problema di percorso, ma di altro.
Ti faccio inoltre una ulteriore domanda.. su iphone, quando mi loggo e
metto la spunta su ricordami alla volta dopo non si ricorda nulla ne mail
ne password.. un po scocciante...si potrebbe secondo te rimediare ?

Grazie !!

Sergio

Il giorno 20 giugno 2018 13:01, David Bigagli <notifications@github.com> ha
scritto:

**Comment by spippolone** [comment]
ovviamente sul pc si ricorda il login e la password...

Il giorno 14 luglio 2018 22:47, spippolone <spippolone@gmail.com> ha
scritto:

**Comment by lejubila** [comment]
Ciao @spippolone 
ho individuato il problema ..... la chiamata json veniva eseguita su una url inconsistente se piGardenWeb non stava nella document root. 
Ho corretto il problema, quindi la procedura da fare è la seguente:
- reinstalla piGardenWeb scaricando l'ultima versione e posizionala in /home/pi/piGardenWeb come indicato nella guida
- crea un link simbolico nella document root in questo modo:
```
cd /var/www
ln -s /home/pi/piGardenWeb piGardenWeb
```
- riavvia apache

ora se vai su 
http://tuo_indirizzo_ip/piGardenWeb 
dovrebbe funzionare correttamente.

Fammi sapere.

**Comment by spippolone** [comment]
Ciao Davide finalmente fra i 1000 impegni ce l'ho fatta...  la modicica
funziona ...

scusami per il ritardo tu sei velocissimo ma in questo periodo vo avanti
mettendo toppe da tutte le parti ....  oggi se ce la faccio collego il
sensore pioggia ;- )

Ciao Sergio



Il giorno 15 luglio 2018 09:55, David Bigagli <notifications@github.com> ha
scritto:
