### ISSUE TITLE
aggiornamento non riuscito

### ISSUE THREAD

**Issue by giannisilv** [lejubila/piGardenWeb#14]
ho provato ad aggiornare con git pull...
ma qualcosa è andato storto, così ho rifatto l'installazione della parte web ma mi esce questo errore
quando faccio
`./artisan key:generate`

mi diceva permessi negati
così ho dato il permesso a tutta la cartella piGardenWeb

ma stavolta esce questo errore:

PHP Parse error:  syntax error, unexpected '=' in /home/pi/piGardenWeb/vendor/laravel/framework/src/Illuminate/Support/Arr.php on line 384

come posso risolvere???

**Comment by lejubila** [comment]
Ciao @giannisilv 
L'ultima versione di piGardenWeb, come insdicato nel file README, necessita almeno del php versione 7.1.3.
Il problema che riscontri è quasi sicuramente dovuto ad una vesrione del php non compatibile.
