### ISSUE TITLE
Cambio url predefinito per possibilità HTTPS

### ISSUE THREAD

**Issue by polcape** [lejubila/piGardenWeb#4]
Mettendo l'istanza di piGardenWeb dietro a un server reverse proxy (in modo da accedere dall'esterno tramite https) la web application non legge l'url su cui si sta facendo l'accesso e quindi scrive i link ai fogli di stile e ai javascript con un url http e non https.
Il browser quindi segnala la pagina come insicura perchè sotto https tenta di caricare degli script in http.

È possibile modificare questo comportamento?

Grazie

**Comment by lejubila** [comment]
Sapresti indicarmi quali sono le risorse che vengono caricate in http anziché https ?

**Comment by polcape** [comment]
Eccole!
![2017-11-02_123945](https://user-images.githubusercontent.com/3648038/32324238-fc57894a-bfca-11e7-81db-613d229cd063.jpg)

**Comment by lejubila** [comment]
Ho fatto una modifica nel brench di sviluppo.
Ho aggiunto un parametro da inserire .env che server per forzare automaticamente in https tutte le url.
Il parametro è il seguente:
APP_FORCE_HTTPS=false

Prova inserire il parametro sopra riportato nel tuo .env, passa al brench di sviluppo fai un pull:
cd ~/piGardenWeb
git checkout develop
git pull

fatto questo verifica se funziona e fammi sapere.

**Comment by polcape** [comment]
Ciao, ti confermo che ora l'errore non viene più restituito.

Problema risolto.

Grazie
