### ISSUE TITLE
Cambiare percorso di default ...

### ISSUE THREAD

**Issue by ghost** [lejubila/piGardenWeb#5]
L'installazione prevede il solo "piGardenWeb", come integrarlo ad una installazione esistente con "meterN" ed "123Solar" ?

Ho installato "piGarden", nella guida manca un pacchetto da installare, almeno sulla mia Raspberry ed è questo "ucspi-tcp". Una volta aggiunto il server è partito regolarmente.

Ho installato "piGardenWeb", spostando il tutto in "/var/www/piGardenWeb" per non toccare la configurazione di "meterN" e "123solar". Accedo quindi con http://raspberry/piGardenWeb/public/" ma cercando di fare la registrazione ottengo un errore :

"The requested URL /piGardenWeb/public/admin/register"

Ho naturalmente sistema tutti i percorsi che facevano riferimento ad "/home/pi/piGardenWeb/".

Esiste un aprocedura semplice ?

**Comment by lejubila** [comment]
Ciao @debugasm 
per quanto riguarda il pacchetto ucspi-tcp, questo è menzionato nel file README di piGarden.
Invece per il posizionamento di piGardenWeb in "/var/www/piGardenWeb" ho provato a riprodurre la tua configurazione sul mio raspberry con apache come webserver ma non ho notato nessun malfunzionamento.
Riesci a darmi maggiori dettagli, magari analizzando i file di log di apache o di laravel che sono in /var/www/piGardenWeb/storage/logs/ ?

**Comment by ghost** [comment]
Ciao @lejubila 
scusami ma hai ragione, ho seguito in modo dettagliato il README di piGardenWeb ed ho installato invece piGarden senza controllare il README.

Ho fatto un'altra prova utilizzando una immagine vergine di RaspBerry (modalità console), ho installato Apache, PHP e successivamente la guida di piGardenWeb (utilizzando il git) ed il problema persiste.

Controllo il file log e ti aggiorno.

**Comment by ghost** [comment]
Ho scaricato il log:
```
[2018-05-13 09:01:08] local.ALERT: Could not register permissions  
[2018-05-13 09:01:13] local.ALERT: Could not register permissions  
```
Non è molto chiaro, ti dice qualcosa ?

**Comment by lejubila** [comment]
Sembra che ci siano problemi nella registrazione dei permessi utente.
Il database è stato creato correttamente  ? 
Di seguito ti riporto i comandi adattati al tuo percorso per creazione e popolazione db + impostazione dei permessi sui file 

```
cd /var/www/piGardenWeb
touch database/piGarden.sqlite
./artisan key:generate
./artisan migrate
sudo chown -R pi:www-data /var/www/piGardenWeb/
sudo chmod -R g+w storage database /var/www/piGardenWeb/database/piGarden.sqlite

```

Se continua a darti problemi sarebbe utile avere tutto il file dei log.

**Comment by ghost** [comment]
Immagino che il tutto vada fatto con utente "pi". I miei comandi erano i medesimi ma continuo ad avere qualche problema. 

Cancello tutto e riparto da capo non appena ho un attimo di tempo. 

Ti tengo aggiornato, grazie mille per adesso.

**Comment by ghost** [comment]
Sono ripartito da una immagine pulita originale raspberry, l'ultima disponibile
sul sito ufficiale. Ho seguito passo passo la guida per piGarden e piGardenWeb,
nessun problema, il tutto funziona come mi aspettavo.

La configurazione che mi interessa utilizza "Apache2" al posto di "nginx" quindi
sono ripartito da una immagine pulita originale raspberry ed ho installato un
LAMP server con "Apache2".

Ho nuovamente seguito la guida per piGarden e piGardenWeb, escludendo "nginx",
l'installazione non ha dato nessun problema, riesco a vedere la "Home" di piGardenWeb, 
se provo a registrarmi ottengo :

```
Not Found

The requested URL /admin/register was not found on this server.
```

Il log è il medesimo:

```
[2018-05-19 15:35:09] local.ALERT: Could not register permissions  
[2018-05-19 15:35:13] local.ALERT: Could not register permissions  
```

 A questo punto posso immaginare che ci sia qualche problema con "Apache2".

Se hai tempo e/o voglia per verificare il problema con "Apache2".

Altre idee ?

**Comment by lejubila** [comment]
Ciao @debugasm anche io uso apache2.
Il file .htaccess dentro la public è accessibile?
Ai modo di farmi collegare alla tua installazione per fare delle verifiche ? Se si lascia un commento sul [blog](https://lejubila.net) lasciando il tuo indirizzo mail nel campo della form e io ti ricontatto in privato.

**Comment by ghost** [comment]
Non appena hai nominato il file ".htaccess" mi è venuto in mente il modulo "mod_rewrite" che non si attiva di default quando installi "Apache2", per cui ho inviato:
```
sudo a2enmod rewrite

sudo systemctl restart apache2
```
e adesso funziona perfettamente, mi sono registrato ed ho avuto accesso. Consiglio magari di aggiungerlo alla guida.

Nella guida di piGardenWeb ho notato che il comando per avviare "piGarden" non è esatto.
```
cd
cd piGarden
./piGarden.sh start_socket_server force
```
Manca estensione ".sh" a "./piGarden".

Adesso devo fare qualche prova, il mio intento è utilizzare una scheda Sonoff a 4 canali per controllare le 4 elettrovalvole del giardino.

Esiste già un driver per questo utilizzo ?

Grazie mille per il supporto.

**Comment by lejubila** [comment]
@debugasm 
perfetto, sono contento che hai risolto.

Riguardo la scheda Sonoff purtroppo ancora non esiste un driver per piGarden. Se mi fai avere qualche specifica vedo cosa posso fare.
