### ISSUE TITLE
Icone irrigazione non aggiornano stato ...

### ISSUE THREAD

**Issue by ghost** [lejubila/piGardenWeb#8]
Facendo qualche prova di irrigazione della durata di pochi minuti mi sono accorto che le icone dello stato di irigazione non si aggiornano. Lasciando aperta la pagina principale della dashboard, una volta terminato il tempo di irrigazione, l'icona della valvola corrispondente non cambia stato (valvola chiusa/aperta) fino a quando non si aggiorna la pagina.

**Comment by lejubila** [comment]
Ciao @debugasm ho provato sul mio pc con chrome come browser è non noto nessun problema, l'interfaccia si aggiorna regolarmente senza dovere ricarica la pagina. L'aggiornamento avviene grazie ad una chiamata ajax che viene eseguita ogni 20 secondi.
Sarebbe utile sapere il tuo caso di utilizzo ovvero con quale browser/versione e sistema operativo riscontri il problema.

Fammi sapere.

**Comment by ghost** [comment]
Ho controllato ed effettivamente l'aggiornamento avviene nel giro di 20/30 secondi. Preso dall'ansia pensavo non funzionasse qualcosa. Tutto risolto.
